apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  containers:
  - image: elasticsearch:8.1.3
    imagePullPolicy: IfNotPresent
    name: elasticsearch
    command:
      - "elasticsearch"
      - "-s"
    resources:
      requests:
        memory: "12Gi"
        cpu: 4
        ephemeral-storage: "10Gi"
      limits:
        memory: "24Gi"
        cpu: 8
    env:
      - name: discovery.type
        value: single-node
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
    name: http
  selector:
    app: elasticsearch
  sessionAffinity: None
  type: ClusterIP
